hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_ban_hang
    Username: root
    password: 10112002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
